name: Build and Publish NPM Package

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to GitHub Packages

      - name: Setup Git identity
        run: |
          git config --global user.email "github.actions@github.com"
          git config --global user.name "Github Actions"

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@sec0ndhand'

      - run: npm ci

      - name: Increment patch version
        run: npm version patch

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "build-v${{ env.PACKAGE_VERSION }}"  # Fixed the env variable issue
          release_name: Release ${{ env.PACKAGE_VERSION }}
          body: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
