name: Increment Patch Version

on:
  push:
    branches:
      - main
      - master

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetch all history for all branches and tags

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Increment patch version and commit
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        npm version patch
        git push
